services:
  filestorage-api:
    env_file: .env
    container_name: filestorage_api
    build:
      context: ./server
    image: filestorage-api
    pull_policy: never
    ports:
      - 5000:80
    volumes:
      - ./server:/opt/server
    environment:
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=5432
      - PGDATABASE=${PGDATABASE}
    depends_on:
      filestorage-db:
        condition: service_healthy
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80", "--reload"]


  filestorage-db:
    env_file: .env
    image: postgres:15-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - ${PGPORT_LOCAL}:5432
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
